Draft and matchmaking implementation
knights-of-academia/pom-bot pull request #28
Opened 2020-12-27 08:50 UTC by debashisbiswas

Teams are assigned only using roles, as we are not storing team information in the database.
These changes handle reactions in the draft, but the bot will still need to send a message for users to react to.

2020-12-28 00:15 UTC, clayboone requested changes
Finished review.

Consider almost all these comments optional. The only one I'm really concerned about is how the bot chooses which team to add a player to.

2020-12-28 00:15 UTC, clayboone commented on pombot/lib/event_handlers.py
> +                team = knight_role
Is this line needed? Maybe leftover from debug? It seems to be set in all future cases.

2020-12-28 00:15 UTC, clayboone commented on pombot/lib/event_handlers.py
> +                if payload.guild_id in Pomwars.KNIGHT_ONLY_GUILDS:
Moving these guild ID's around is going to be messy... I don't have a solution, just an observation.

2020-12-28 00:15 UTC, clayboone commented on pombot/lib/types.py
> +class InstantItem(str, Enum):
Did we not rename this? Or is this the new name..

2020-12-29 11:25 UTC, debashisbiswas commented
Updated to add the user to the database, with changes made based on most of the above comments.

2020-12-29 20:16 UTC, merged