Changed formatting for attack and defend
knights-of-academia/pom-bot pull request #51
Opened 2021-01-02 17:59 UTC by zmontgo

2021-01-02 18:21 UTC, clayboone requested changes

2021-01-02 18:21 UTC, clayboone commented on pombot/cogs/pom_wars_commands.py
> +        title = f"You have used {indicator}Attack against the {{team}}!".format(
Please don't format an f-string. There's a better, easier way to do this

2021-01-02 18:21 UTC, clayboone commented on pombot/cogs/pom_wars_commands.py
> +    def get_color(self) -> str:
This doen's return a `str`

2021-01-02 18:21 UTC, clayboone commented on pombot/cogs/pom_wars_commands.py
> +        action = f"** **\n{Pomwars.Emotes.DEFEND} `2% team damage reduction!`".format(
This markdown looks weird. Do you have a screenshot of the result?

Also: the defend amount is not static. In the original bransh, this line is correct, mathematically and this changes functionality.

2021-01-02 18:21 UTC, clayboone commented on pombot/cogs/pom_wars_commands.py
> +    def get_title(self, user: User) -> str:
we don't need non-reusable, single-line functions.

2021-01-02 18:21 UTC, clayboone commented on pombot/cogs/pom_wars_commands.py
> +            icon_url=None,
Do we ever expect this to be `None` ?

2021-01-02 18:21 UTC, clayboone commented on pombot/config.py
> +    ACTION_COLOUR = 0xF5F5DC
All colors should be here (see the other branch; it's handled sanely).

2021-01-02 18:21 UTC, clayboone commented on pombot/data/pom_wars/heavy_attacks/~criticals/poisoned_truce/message.txt
> +you switch cups when he isn't looking.
What changed here?

2021-01-02 18:21 UTC, clayboone commented on pombot/lib/messages.py
> +    if (icon_url):
This is a thin wrapper that switches on function, not icon. I see no need to change it.

2021-01-02 20:19 UTC, zmontgo commented on pombot/cogs/pom_wars_commands.py
> +        action = f"** **\n{Pomwars.Emotes.DEFEND} `2% team damage reduction!`".format(
![image](https://user-images.githubusercontent.com/31627113/103465858-0fc9f100-4d05-11eb-8c59-2575546b62f3.png)
The bold space prevents Discord from trimming it, to give some space between the title and the description.

I forked from master/develop, which is why mine did not have the changes, but I'm adding them in.

2021-01-02 20:49 UTC, zmontgo commented on pombot/cogs/pom_wars_commands.py
> +            icon_url=None,
Yes, that was part of my edit. If the icon is `None` it will not set the author but instead set the title as the Embed's title.

2021-01-02 20:52 UTC, zmontgo commented on pombot/lib/messages.py
> +    if (icon_url):
The icon cannot be left blank if you're using a user in an embed. Alex wanted to omit the user logo sometimes and just use a title, so this just checks if we want to include the user icon or not.

2021-01-02 21:28 UTC, zmontgo commented on pombot/data/pom_wars/heavy_attacks/~criticals/poisoned_truce/message.txt
> +you switch cups when he isn't looking.
New line was removed that was breaking the italics.

2021-01-02 21:36 UTC, zmontgo commented on pombot/lib/messages.py
> +    if (icon_url):
I've left this open because I didn't change it. Sending no `icon_url` doesn't omit it, Discord forces there to be one so chooses one somehow. It showed the Pom image whenever I omitted it, so I made this wrapper to make sure we could have a title without an image.

2021-01-03 02:15 UTC, zmontgo commented on pombot/cogs/pom_wars_commands.py
> +    def get_title(self, user: User) -> str:
I left the one for attack so I could get the class's `self.is_heavy` and include that in the title.

2021-01-03 16:38 UTC, clayboone commented on pombot/data/pom_wars/heavy_attacks/~criticals/poisoned_truce/message.txt
> +you switch cups when he isn't looking.
Please correct the code, not the file. Every file should end with a blank line because [that's the correct way to write a text file](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206).

If we "correct" the file, then we've just invented a new file format without a name that we'll need to ensure each story-writer adheres to.

I should be able to create a story file with this content:

```
\n
Some stuff happens.\n
\n
\n
\n
```

And it should format correctly, regardless of newlines.

This is more for future reference because I know there are other "broken" story files apart from this one.

2021-01-03 16:39 UTC, clayboone commented on pombot/data/pom_wars/heavy_attacks/~criticals/poisoned_truce/message.txt
> +you switch cups when he isn't looking.
PPB-36

2021-01-03 23:55 UTC, clayboone requested changes
There are a couple big ones on here. I expected most of them to be about little syntax changes here and there.. Sorry.

2021-01-03 23:55 UTC, clayboone commented on pombot/cogs/pom_wars_commands.py
> +                ],
Ugly hanging `]`. It should be on line 130 without a trailing comma. If you prefer it on a new line, remove 4 spaces from the indent (and the comma).

2021-01-03 23:55 UTC, clayboone commented on pombot/cogs/pom_wars_commands.py
> +            colour=attack.get_color(),
Please keep the spelling the same: `get_colour`. It's spelt this way in discord.py, not because I'm british (i'm not).

2021-01-03 23:55 UTC, clayboone commented on pombot/cogs/pom_wars_commands.py
> +        score = Scoreboard(self.bot, State.SCOREBOARD_CHANNELS)
I'm seeing this a few times now. Why are you passing around stored internal state instead of importing it?

Also: why are you re-instantiating a `Scoreboard` object at all? Couldn't you create a single `Scoreboard`, store it on `pombot.state.State`, have it re-use the `SCOREBOARD` that it builds, and simply call

```python
State.update_scoreboard()
```

at the end of this function?

2021-01-03 23:55 UTC, clayboone commented on pombot/cogs/pom_wars_commands.py
> +        await score.create_msg()
Does `!defend` add any damage? Does this change the scoreboard at all? I'm not sure it needs to be called after a defend action.

2021-01-03 23:55 UTC, clayboone commented on pombot/cogs/pom_wars_commands.py
> +        # It has exception handling to tell what the error is, so we cannot use the class.
Are you sure it can't be a boolean flag?
```python
class Scoreboard:
  def create_msg(handle_exceptions=False)
```

Copy/pasted code only belongs in tests. ;)

2021-01-03 23:55 UTC, clayboone commented on pombot/config.py
> +    NORMAL_COLOR = 0xec5c5b # Normal attack
`COLOUR` for all of them.

Shouldn't `NORMAL_COLOUR` be the same color as `Config.EMBED_COLOUR` ?

2021-01-03 23:55 UTC, clayboone commented on pombot/lib/event_handlers.py
> -
Readd this line, please.

2021-01-03 23:55 UTC, clayboone commented on pombot/lib/messages.py
> +            )
Magic field and magic numbers. How about

```python
if fields:
  try:
    name, value, inline = field
    message.add_field(name, value, inline)
    # or even
    message.add_field(*field) # depends on how add_field is implemented
  except ValueError:
    # come to think about it, you should probably not
    # try/catch here.. let errors happen.
```

2021-01-03 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +    """Handle dynamic scoreboard"""
`"""A representation of the scoreboard in join channels."""

2021-01-03 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +        return str(team)
Why are you converting to a string instead of returning a Team object and letting the caller figure out how to use it?

2021-01-03 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +        return str(team)
2nd read: Why are you returning a string instead of an int?

2021-01-03 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +            action_was_attack = action.type == 'normal_attack' or action.type == 'heavy_attack'
Magic strings; repeated condition..

```python
was_attack = action.type in [ActionType.NORMAL_ATTACK, ActionType.HEAVY_ATTACK]
```

2021-01-03 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +                count += 1
Why are you comparing a `bool` to an `int`?

```python
if action.was_successful and action_was_attack:
  count += 1
```

Or, outrageously:

```python
count += action.was_successful and action_was_attack
```

2021-01-03 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +        return str(count)
A function who's name ends in "`_count`" should probably return an `int`.

2021-01-03 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +        prettyteam = self.viking_actions if team == Team.VIKINGS else self.knight_actions
I don't like this variable name. Is the team pretty? Where's the underscore?

2021-01-03 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +                heavy_count += 1
Use `collections.Counter`.

2021-01-03 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +        return fav # In the rare case it's equal it will return as normal attack
This comment repeats code.

2021-01-03 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +    async def create_msg(self) -> bool:
This appears to be updating an existing message. Shouldn't the name reflect that?

2021-01-03 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +    async def create_msg(self) -> bool:
Why does it return anything? As a side-effect function, it should return `None` (the default) or raise an exception when there's an error. Let the caller deal with it.

2021-01-03 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +                winner = 'knight'
Magic values. use `Team.KNIGHT` or `Config.KNIGHT_ROLE`, whichever is more appropriate (`Config`, I believe)

2021-01-03 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +                        "\n".join(lines).format(**knight_values),
Nice!

2021-01-03 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +                        True
I don't generally like seeing random, unnamed flags hanging around. I've seen the modified function that uses this, but can't remember what it does. Maybe this should pass a dictionary instead of a list.

This is an ignorable change, just try to not have random `true` here and there. This is not a javascript callback ;)

2021-01-04 00:07 UTC, zmontgo commented on pombot/scoreboard.py
> +                        "\n".join(lines).format(**knight_values),
Thanks!

2021-01-04 00:16 UTC, zmontgo commented on pombot/config.py
> +    NORMAL_COLOR = 0xec5c5b # Normal attack
`NORMAL_COLOUR` is the color of a normal attack. Is that what `EMBED_COLOUR` is?

2021-01-04 00:18 UTC, zmontgo commented on pombot/scoreboard.py
> +        return str(team)
String is used more often, int is used in this specific case so I'm using string instead of int.

2021-01-04 01:22 UTC, zmontgo commented on pombot/config.py
> +    NORMAL_COLOR = 0xec5c5b # Normal attack
Looked at it closer. No, I don't think they should be the same. But I have updated `Config.EMBED_COLOR` to have a different default.

2021-01-04 02:13 UTC, zmontgo commented
Everything has been fixed, tested, and linted. One thing, may want to look at lines 68 and 69 in `scoreboard.py`, I'm not sure that's how you're supposed to break that line up.

2021-01-04 20:07 UTC, clayboone requested changes
Last review, i promise!

2021-01-04 20:07 UTC, clayboone commented on pombot/scoreboard.py
> +    def attack_count(self, team) -> int:
```python
    def attack_count(self, team) -> int:
        """Return the total attacks (whether successful or not) of a team."""
        self.update_vars()

        team_actions = self.viking_actions if team == Team.VIKINGS else self.knight_actions
        attack_types = [ActionType.NORMAL_ATTACK, ActionType.HEAVY_ATTACK]
        count = len([a for a in team_actions if a.type in attack_types and a.was_successful])

        return count
```

2021-01-04 20:07 UTC, clayboone commented on pombot/scoreboard.py
> +        return [full_channels, restricted_channels] if handle_exceptions else True
So this either returns a list (len == 2) or a single boolean?

2021-01-04 20:07 UTC, clayboone commented on pombot/cogs/pom_wars_commands.py
> +        full_channels, restricted_channels = await State.score.update_msg(True)
Random `True` flag here: what does it do? (spell out the argument it's supplying, `handle_exceptions=True`)

Also, there's a chance for this function to return a single `True` causing a `ValueError` here.

`Score.update_msg` is a side-effect function and, in this case, should return a list in all cases. Why does it need to return a bool at all?

2021-01-04 21:21 UTC, zmontgo commented on pombot/cogs/pom_wars_commands.py
> +        full_channels, restricted_channels = await State.score.update_msg(True)
I’ll do this. I also forgot to fix the random `True` flag for the `message_embed.add_field()`’s inline property, so I’ll fix both of these things.

2021-01-04 23:03 UTC, zmontgo commented on pombot/cogs/pom_wars_commands.py
> +        full_channels, restricted_channels = await State.score.update_msg(True)
Never mind looks like I can't do the add_field, it has to be like that.

2021-01-04 23:12 UTC, zmontgo commented
Change requests completed, tested, linted. I think everything is good to merge!

2021-01-04 23:31 UTC, merged