slight refactor, added reaction prompt back to draft msg
knights-of-academia/pom-bot pull request #54
Opened 2021-01-06 23:44 UTC by debashisbiswas

2021-01-06 23:55 UTC, clayboone requested changes
Nice bit of clean up. Couple easy comments for ya.

2021-01-06 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +            if action.raw_damage and action.raw_damage > 0:
Why is this extra check needed?

2021-01-06 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +                    True
What does this do?

Since this is Python 3.9, and given that this is a list, could you do something like

```python
[
...
...
(remove_flag_variables := True)
]
```

If it works, then it would tell us what the random flag does and won't need a custom class to do the same thing.

2021-01-06 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +                    True
I don't know what this particular `True` does, but I'd like to, and I'd like the variable name to tell me (I presume it does not, in fact, remove hanging flag variables 😉).

2021-01-06 23:55 UTC, clayboone commented on pombot/scoreboard.py
> +                    True
Commenting here as to not forget when resolving the previous comment.

2021-01-06 23:57 UTC, clayboone commented on pombot/scoreboard.py
> +            if action.raw_damage and action.raw_damage > 0:
To clarify, would this work instead?

```python
if action.raw_damage:
  ...
```

2021-01-07 00:08 UTC, debashisbiswas commented on pombot/scoreboard.py
> +            if action.raw_damage and action.raw_damage > 0:
action.raw_damage can be None due to how we're storing it in the database, so this change was to avoid the error caused by checking None > 0. Your change handles both checks though, I'll update it.

2021-01-07 00:12 UTC, debashisbiswas commented on pombot/scoreboard.py
> +                    True
The `fields` variable was declared twice in the same way, so my change was to move it up such that we declare once and reuse it. I don't know what this `True` does either, so I should update this :)

2021-01-07 02:07 UTC, debashisbiswas commented
Responded to the changes. I refactored a bit more to consolidate some of the repeated code, now that I was already editing this section. Let me know if it was too much

2021-01-08 17:49 UTC, clayboone approved these changes
Only optional changes and a question. LGTM 🦄

2021-01-08 17:49 UTC, clayboone commented on pombot/scoreboard.py
> +            team_fields_inline = True
Perfect 👍

2021-01-08 17:49 UTC, clayboone commented on pombot/scoreboard.py
> +                    _func=func,
```python
_func=scoreboard_msg.edit if scoreboard_msg else channel.send
```

2021-01-08 17:49 UTC, clayboone commented on pombot/scoreboard.py
> +            if scoreboard_msg:
Seems out of place, could you in-line this?

2021-01-08 17:49 UTC, clayboone commented on pombot/scoreboard.py
> +                new_msg = await send_embed_message(
I guess this returns `None` when only editing the message?

2021-01-08 19:00 UTC, debashisbiswas commented on pombot/scoreboard.py
> +                new_msg = await send_embed_message(
That's correct, I wasn't sure what to do to make it more clear

2021-01-08 19:17 UTC, merged