Timezone DM command
knights-of-academia/pom-bot pull request #60
Opened 2021-01-14 04:59 UTC by debashisbiswas

This is not ready in its current state - making a PR to get some more eyes on it.
Here's a summary of what's in here so far.
- `!timezone` implementation - command in bot DM, this is done (other than checking to see if the user is abusing it). `!timezone` shows your currently set timezone, `!timezone <offset>` allows you to set your timezone. 
- Applying the user timezone setting to `!actions` and in chance functions - this is where I'll need a second opinion on a cleaner way to approach this than what I've done so far

2021-01-15 00:00 UTC, clayboone requested changes
Draft code review :)

2021-01-15 00:08 UTC, clayboone commented on pombot/config.py
> -    RESPOND_TO_DM = _str2bool(os.getenv("RESPOND_TO_DM", "no"))
Ah, so then it shouldn't be in `Debug` anymore either.

2021-01-15 00:26 UTC, clayboone commented on pombot/cogs/pom_wars_commands.py
> +        if isinstance(ctx.channel, DMChannel):
For example, when this is merged to master and the normal `user_commands` cog is loaded, then users will now be able to log poms by chatting with the bot instead of chatting in the #pom-bank (or whatever the channel is called).

2021-01-20 05:43 UTC, debashisbiswas commented on pombot/config.py
> -    RESPOND_TO_DM = _str2bool(os.getenv("RESPOND_TO_DM", "no"))
Added this flag back to the config file. I went with the next comment and set up a whitelist for DM-only commands that bypasses this debug flag. It still works as previously, just applies for the other commands that normally wouldn't work in DMs. Did you still want the pomwar cog to fail to load?

2021-01-20 05:44 UTC, debashisbiswas commented on pombot/cogs/pom_wars_commands.py
> +                description="That is not a valid UTC offset. Please specify a " \
Doesn't look like Python handles the human readable offsets very well - how do you feel about the `pytz` library?

2021-01-21 21:05 UTC, clayboone commented on pombot/config.py
> -    RESPOND_TO_DM = _str2bool(os.getenv("RESPOND_TO_DM", "no"))
Nah, what you've done sounds reasonable.

2021-01-21 21:10 UTC, clayboone commented on pombot/cogs/pom_wars_commands.py
> +                description="That is not a valid UTC offset. Please specify a " \
Realistically, we only need a mapping something like

```python
human_readable_timezones = {
  "BST": +1,
  "UTC": +0,
  ...
  "CST": -6,
}
```

I'd rather not have an entire extra dependency just for one dictionary. I say we either come up with a `dict` like this or just leave this nicety alone for now and see if users complain about it being missing.

2021-02-10 23:38 UTC, closed without merging